### ISSUE TITLE
Not reporting best match?

### ISSUE THREAD

**Issue by tieguy** [licensee/licensee#348]
### Describe the bug

`licensee detect` seems to report a lower-scoring result as the best match for
 https://github.com/ThreeTen/threetenbp/blob/master/LICENSE.txt

### Steps to reproduce the behavior

1. run `licensee detect` on https://github.com/ThreeTen/threetenbp/blob/master/

result (snipped):

`License:        NOASSERTION`
`  Closest non-matching licenses:`
`    BSD-3-Clause-Clear similarity:  91.34%`

run `licensee diff --license bsd-3-clause-clear` on LICENSE.txt:

`Comparing to BSD 3-Clause Clear License:`
`Input Length: 1402`
`License length: 1556`
`Similarity: 94.65%`

run `licensee diff --license bsd-3-clause` on LICENSE.txt:

`Comparing to BSD 3-Clause "New" or "Revised" License:`
`Input Length:      1402`
`License length:    1416`
`Similarity:      98.29%`

`detect` and `diff` seem to substantially disagree on what the best match is, and the actual match (one word, plus copyright holder -> specific copyright holder name) is probably close enough that `detect` should report bsd-3-clause.

### Expected behavior

`detect` reports bsd-3-clause, not bsd-3-clause-clear, as the closest match.

### Additional context

Possibly related to #347.

**Comment by benbalter** [comment]
On `master` I get the following results:

```
be licensee detect --remote https://github.com/ThreeTen/threetenbp
License:        NOASSERTION
Matched files:  LICENSE.txt
LICENSE.txt:
  Content hash:  10024377604b3673aaa87223ee03fd38c7205e6b
  License:       NOASSERTION
  Closest non-matching licenses:
    BSD-3-Clause-Clear similarity:  92.13%
```

```
be licensee diff --license bsd-3-clause-clear --remote https://github.com/ThreeTen/threetenbp
Comparing to BSD 3-Clause Clear License:
Input Length:      1557
License length:    1562
Similarity:      92.13%
diff --git a/LICENSE b/LICENSE
index eed934d..1ff0601 100644
--- a/LICENSE
+++ b/LICENSE
@@ -1,21 +1,20 @@
{+/* - copyright (c) 2007-present, stephen colebourne and michael nascimento+}
{+santos - * all rights reserved. - *+} redistribution and use in source and binary
forms, with or without {+-+} modification, are permitted[-(subject to the limitations in the disclaimer below)-] provided that the following
conditions are met: - redistributions of source code must retain the above
copyright notice, {+-+} this list of conditions and the following disclaimer. -
redistributions in binary form must reproduce the above copyright notice, {+-+} this
list of conditions and the following disclaimer in the documentation {+-+} and/or
other materials provided with the distribution. - neither the name of [-the copyright holder-]{+jsr-310+}
nor the names of its contributors {+-+} may be used to endorse or promote products
derived from this software {+-+} without specific prior written permission. [-no express or implied licenses to any party's patent rights-]
[-are granted by this license.-]{+- *+} this
software is provided by the copyright holders and contributors {+-+} "as is" and any
express or implied warranties, including, but not {+-+} limited to, the implied
warranties of merchantability and fitness for {+-+} a particular purpose are
disclaimed. in no event shall the copyright holder or {+-+} contributors be liable
for any direct, indirect, incidental, special, {+-+} exemplary, or consequential
damages (including, but not limited to, {+-+} procurement of substitute goods or
services; loss of use, data, or {+-+} profits; or business interruption) however
caused and on any theory of {+-+} liability, whether in contract, strict liability,
or tort (including {+-+} negligence or otherwise) arising in any way out of the use
of this {+-+} software, even if advised of the possibility of such damage. {+*/+}
```

```
be licensee diff --license bsd-3-clause --remote https://github.com/ThreeTen/threetenbp
Comparing to BSD 3-Clause "New" or "Revised" License:
Input Length:      1557
License length:    1420
Similarity:      94.69%
diff --git a/LICENSE b/LICENSE
index e57f70e..1ff0601 100644
--- a/LICENSE
+++ b/LICENSE
@@ -1,19 +1,20 @@
{+/* - copyright (c) 2007-present, stephen colebourne and michael nascimento+}
{+santos - * all rights reserved. - *+} redistribution and use in source and binary
forms, with or without {+-+} modification, are permitted provided that the following
conditions are met: - redistributions of source code must retain the above
copyright notice, {+-+} this list of conditions and the following disclaimer. -
redistributions in binary form must reproduce the above copyright notice, {+-+} this
list of conditions and the following disclaimer in the documentation {+-+} and/or
other materials provided with the distribution. - neither the name of [-the copyright holder-]{+jsr-310+}
nor the names of its contributors {+-+} may be used to endorse or promote products
derived from this software {+-+} without specific prior written permission. {+- *+} this
software is provided by the copyright holders and contributors {+-+} "as is" and any
express or implied warranties, including, but not {+-+} limited to, the implied
warranties of merchantability and fitness for {+-+} a particular purpose are
disclaimed. in no event shall the copyright holder or {+-+} contributors be liable
for any direct, indirect, incidental, special, {+-+} exemplary, or consequential
damages (including, but not limited to, {+-+} procurement of substitute goods or
services; loss of use, data, or {+-+} profits; or business interruption) however
caused and on any theory of {+-+} liability, whether in contract, strict liability,
or tort (including {+-+} negligence or otherwise) arising in any way out of the use
of this {+-+} software, even if advised of the possibility of such damage. {+*/+}
```

It's not properly normalizing the border, which is a bug in itself, but I believe the similarity percentages are as expected?

**Comment by mlinksva** [comment]
I'd bet (based on past experience/looking at the code, haven't tested this case) in the `license detect` case above `bsd-3-clause-clear` is not a candidate for a match because its length differs from the expected for that license by too much, so its similarity is not calculated, so it can't be listed as one of the most similar licenses. I've looked into mitigating some unexpected results like this with very long or short licenses e.g., #242 but am not sure there is a 'right' answer.

**Comment by tieguy** [comment]
Noting that I've found a similar failure condition again. 

licensee version
9.13.1

Running on: https://github.com/rspec/rspec-mocks/blob/v3.9.1/LICENSE.md

> licensee detect rspec-mocks-3.9.1/LICENSE.md 
> License:        NOASSERTION
> Matched files:  LICENSE.md
> LICENSE.md:
>   Content hash:  34a725c6d925c2608c82199eb8963bd3b5b16b71
>   License:       NOASSERTION
>   Closest non-matching licenses:
>     Unlicense similarity:  58.65%

License is actually MIT, confirmed by:

> licensee diff rspec-mocks-3.9.1/LICENSE.md --license mit
> Comparing to MIT License:
> Input Length:      1165
> License length:    1020
> Similarity:      93.88%
> diff --git a/LICENSE b/LICENSE
> index 0ce42af..ba43f2e 100644
> --- a/LICENSE
> +++ b/LICENSE
> @@ -1,8 +1,10 @@
> {+- copyright © 2012 david chelimsky, myron marston - copyright © 2006 david+}
> {+chelimsky, the rspec development team - copyright © 2005 steven baker+} permission
> is hereby granted, free of charge, to any person obtaining a copy of this
> software and associated documentation files (the "software"), to deal in the
> software without restriction, including without limitation the rights to use,
> copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
> software, and to permit persons to whom the software is furnished to do so,
> subject to the following conditions: the above copyright notice and this
> permission notice shall be included in all copies or substantial portions of the
> software. the software is provided "as is", without warranty of any kind,

>

**Comment by mlinksva** [comment]
I'd bet...same as above https://github.com/licensee/licensee/issues/348#issuecomment-448893091
