### ISSUE TITLE
Add git repo ref argument to GithubProject#load_file

### ISSUE THREAD

**Issue by benwiley4000** [licensee/licensee#351]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

licensee is awesome - thank you! It would be even better if it were possible to specify a ref version when fetching a license from a remote GitHub repo. As-is, it's a bit unreliable/unsafe from a legal perspective to fetch the license in the latest commit when that might be inconsistent with the version of the dependency you are using.

### Describe the solution you'd like

licensee commands which accept the `[PATH]` argument should also accept a `--ref` argument which is a string to be processed by the GitHub API.

Note that [refs can be passed to the GitHub contents API](https://github.com/octokit/octokit.rb#additional-query-parameters):

```rb
 client.contents('octokit/octokit.rb', path: 'path/to/file.rb', query: {ref: 'some-other-branch'})
```

### Describe alternatives you've considered

One alternative is to do licensees's work manually and make several requests to the GitHub contents API for different license file name strings. At that rate, we should just be merging a feature into licensee, I think.

### Additional context

This is especially useful for dependencies which are developed in monorepos, such as the popular npm libraries React, Jest and Babel. They have many sub-packages which are distributed individually on npm and in some cases the library authors forget to include the actual license text in the package, even though it is available at the root of the repository on GitHub. In order to ensure we fetch the proper version, we want to specify a tag ref which can be derived from the version string.

**Comment by benwiley4000** [comment]
I ended up implementing this feature locally and I may be able to open a PR if you'd be interested.

**Comment by benbalter** [comment]
> I ended up implementing this feature locally and I may be able to open a PR if you'd be interested.

Yes please! I think it's a great idea.

**Comment by benwiley4000** [comment]
I have a PR to offer finally... sorry for the long delay!
