### ISSUE TITLE
bin doesn't work when installed from git

### ISSUE THREAD

**Issue by benwiley4000** [licensee/licensee#355]
I'm kind of new to Ruby so I'm not 1000% convinced this is a bug and not user error, but it sort of feels like a bug.

### Describe the bug

bin errors out when fetching via git (either in a Gemfile with a git source, or cloning the repo locally)

### Steps to reproduce the behavior

1. Git clone the repo
2. `script/bootstrap`
3. Try running:

```
bin/licensee
```

.. every time I get this error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- licensee/projects (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wileyb/licensee/lib/licensee.rb:43:in `rescue in project'
	from /Users/wileyb/licensee/lib/licensee.rb:37:in `project'
	from bin/licensee:25:in `project'
	from /Users/wileyb/licensee/lib/licensee/commands/detect.rb:23:in `detect'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from bin/licensee:37:in `<main>'
```

I figured this was an issue since the last release so I did:
4. `git checkout v9.10.1`
5. `script/bootstrap`
6. `bin/licensee`

But I see the same thing.

### Expected behavior

Works the same as the gem from the registry

**Comment by benwiley4000** [comment]
Oops, I needed to run `bundle exec licensee` not `bin/licensee` ... not sure if this is still a bug at this point or if that's user error. Thoughts?

**Comment by benbalter** [comment]
I suspect this is an issue with the `lib` dir not being in Ruby's loadpath, which the project should be able to fix programmatically (i agree what you describe should be the expected behavior).

If you have bundler installed, `bundle exec licensee` or `bundle exec bin/licensee` should fix it.
