### ISSUE TITLE
Can you add internationalization to the license? Such as Chinese

### ISSUE THREAD

**Issue by ouyangshi95** [licensee/licensee#364]
### Describe the solution you'd like
Hi! Thank you very much for making this gem, It is very good and useful. Dut to my dismay, the license does not support internationalization. I hope to have the license has Chinese described. Can you help me?

**Comment by mlinksva** [comment]
Are you referring to the messages in the licensee (command line) UI? I don't see any previous request or effort toward that in this repo but I guess there must be well established best practices for adding to a command line Ruby program, subject to the maintainer's interest.

If you're referring to licenses themselves, that's out of scope for this repo. If there are open source licenses that are written in Chinese it would be best to put them through the processes of https://opensource.org/approval and https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md ... frankly there aren't many open source licenses in languages other than English, but that doesn't mean there shouldn't be. Licensee detects certain very well known licenses, so for any new license, in any language, the place to start is by making them known through existing processes.
