### ISSUE TITLE
Recognize REUSE Initiative markup in LICENSE files?

### ISSUE THREAD

**Issue by lassik** [licensee/licensee#366]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I read that GitHub is using this gem to detect the license of each repository. If I have a `LICENSE` file in my repo with a verbatim copy of e.g. the BSD-2-Clause license, then it correctly shows up as `BSD-2-Clause`. However, if I add the following markup at the beginning of that `LICENSE` file:

    Valid-License-Identifier: BSD-2-Clause
    License-Text:

    <...full text of the BSD-2-Clause license here, as usual...>

then it's detected as an unknown license.

This markup is used by the [REUSE Initiative](https://reuse.software/practices/2.0/) so that their software tools can determine what license is in question. The current situation is that I can have either GitHub or the REUSE tool determine the correct license, but not both at the same time :) The REUSE conventions require the markup in the `LICENSE` file even for well-known licenses.

### Describe the solution you'd like

Would it be possible to add support for the REUSE markup to *licensee*?

It could simply do a regexp or string match for the markup at the beginning of each `LICENSE ` file, perhaps after normalizing  whitespace. There ought to be few (if any) variations in how the markup is written. Luckily, the `Valid-License-Identifier`s they use are the exact same ones as the `SPDX-License-Identifier`s that *licensee* is already using.

### Describe alternatives you've considered

I'm not using *licensee* for anything other than convenience, so this is not critical.

### Additional context

Here's [an example repo of mine](https://github.com/lassik/go-httplog)

**Comment by mlinksva** [comment]
As you say this would be easy to support in licensee. It looks to be used a bit so far, https://github.com/search?p=2&q=Valid-License-Identifier&type=Code obtains 9046 results.

A couple questions:

- Is there a spec to go along with the REUSE best practices document? I couldn't find one. I ask in part because some of the results above have additional key-value like entries which would be harder for licensee to support to the extent the values are free-form text. Example: https://github.com/rajanvaja/linux/blob/5c60a7389d795e001c8748b458eb76e3a5b6008c/LICENSES/preferred/MIT
- Are Valid-License-Identifier and License-Text (and anything else from above) being discussed for inclusion in the SPDX matching guidelines?

**Comment by mlinksva** [comment]
By the way, the most attractive part of supporting Valid-License-Indentifier to me is that it provides a way to indicate `-or-later` or `-only` for _GPL licenses in a single `LICENSE` file, something which I've [wished for](https://github.com/benbalter/licensee/issues/85#issuecomment-192719864) but didn't know of any push to standardize so left the wish to idle. 😄

**Comment by lassik** [comment]
Thanks for the great response :) Those are all good questions!

> Is there a spec to go along with the REUSE best practices document? I couldn't find one.

Unfortunately, I can find neither a formal spec nor an address to contact the authors of the guidelines. The campaign is promoted by [Free Software Foundation Europe](https://fsfe.org/) but I don't know who to contact in that organization. The command line tool `reuse` is their main software tool: https://gitlab.com/reuse/reuse. We could try asking the authors of that tool.

>  I ask in part because some of the results above have additional key-value like entries which would be harder for licensee to support to the extent the values are free-form text. Example: https://github.com/rajanvaja/linux/blob/5c60a7389d795e001c8748b458eb76e3a5b6008c/LICENSES/preferred/MIT

Good catch. As far as I can tell, those seem to be non-standard extensions - those tags are mentioned in neither the `reuse` tool's source code nor in the guidelines. Maybe this algorithm would work:

* If the file starts with the line `Valid-License-Identifier: ...`
* Then skip any following lines that are in `Tag: Value` format or start with whitespace
* Until the tag `License-Text:` is found. Then stop parsing. Treat everything after that line as the license text.
* If `Valid-License-Identifier:` and `License-Text:` were not both found, this is not a REUSE compliant license file. Fall back to other approaches.

> Are Valid-License-Identifier and License-Text (and anything else from above) being discussed for inclusion in the SPDX matching guidelines?

No idea about this, as I have detailed knowledge of neither SPDX nor REUSE, just a happy user :) SPDX are big on manifest files - I don't know what their stance is on including the full license text in the repo. We should ask some people from those organizations. It seems like they have very compatible goals.

For what it's worth, the `reuse compile` command auto-generates a manifest in the SPDX format.

> By the way, the most attractive part of supporting Valid-License-Indentifier to me is that it provides a way to indicate `-or-later` or `-only` for _GPL licenses in a single `LICENSE` file

Alas, I think that is not possible, or not recommended at any rate. But they have a solution that's even better in my opinion.

I think their idea is to have the comments

    # Copyright year author
    # SPDX-License-Identifier: license

in each source file, and *additionally* put the full text of each license in a text file in a standard place. Running `reuse lint` produces warnings for source files that don't have those comments even if you have a `LICENSE` file. This is probably a sound design choice, as licensing of individual files is often unclear in projects that have copied code from many other projects. Better to be explicit, and anyway that's only a couple lines of code, so it's not as obtrusive as putting a big license header in each source file.

Another thing is that it's possible to e.g. have some source files under `GPL-2.0-only` and other files  under `GPL-2.0-or-later` if those files came from different places. I think the REUSE idea is to store the full text of each license only once, and use `SPDX-License-Identifier`s in source files to specify the details.

They also suggest a `LICENSES` directory instead of a `LICENSE` file for projects with multiple licenses. IMHO that's a super elegant solution to the problem. Here's an example of it: https://gitlab.com/reuse/reuse/tree/master/LICENSES.

The [readme for that tool](https://gitlab.com/reuse/reuse/blob/master/README.rst) says:

> A special note on the GPL: If you use `Valid-License-Identifier: GPL-3.0` or name the file `LICENSES/GPL-3.0.txt`, this will catch all the following licenses: `GPL-3.0`, `GPL-3.0+`, `GPL-3.0-only` and `GPL-3.0-or-later`. This applies to the entire GPL family of licenses.

And indeed, they have a `GPL-3.0.txt` in their `LICENSES` directory and [the source files](https://gitlab.com/reuse/reuse/tree/master/src/reuse) say `SPDX-License-Identifier: GPL-3.0-or-later`.

> As you say this would be easy to support in licensee. It looks to be used a bit so far, https://github.com/search?p=2&q=Valid-License-Identifier&type=Code obtains 9046 results.

Awesome to hear that it's catching on :) I didn't think of doing a search :D

**Comment by lassik** [comment]
> There ought to be few (if any) variations in how the markup is written.

Also, this should be another lesson to me to never say things like this again :D

**Comment by mlinksva** [comment]
According to https://reuse.software/practices/2.0/ is is possible to have `Valid-License-Identifier: GPL-2.0+` in a `LICENSE` file. They obviously haven't updated the guide since `-or-later` became preferred to `+`. 

SPDX is several things, the ones I have in mind here are the https://spdx.org/spdx-license-list/matching-guidelines which work together with the license file templates in https://github.com/spdx/license-list-XML/ which together specify what for any particular license text is mandatory, optional, etc. It seems to me any annotation scheme that wishes to be widely supported in `LICENSE` files really ought to be driven through the SPDX matching guidelines which various license detection tools implement to varying degrees.

I'll leave this open to gather more info for now since I'm not likely to work on it soon! 😬

**Comment by lassik** [comment]
OK, you're right, I missed this right in the [REUSE practices](https://reuse.software/practices/2.0/):

> The license identifier may be repeated if the same license file is used with multiple license identifiers. The example below is for GPL-2.0 and GPL-2.0+, but please note that it is not mandatory to list GPL-2.0+ separately.
>
>     Valid-License-Identifier: GPL-2.0
>     Valid-License-Identifier: GPL-2.0+

Also:

> In the unlikely event your source code includes exceptions, such as the Classpath exception 2.0, you may include them *in the same place* as your licenses, using the same header style or the tags SPDX-Exception-Identifier and Exception-Text instead. This is an example of a valid exception:
>
>     SPDX-Exception-Identifier: Classpath-exception-2.0
>     Exception-Text:
>
>     Linking this library statically or dynamically with other modules is
>     making a combined work based on this library. Thus, the terms and
>     conditions of the GNU General Public License cover the whole combination.

Not sure what *in the same place* means here - I think it means the `LICENSES` directory, not same license file. So although the files in the `LICENSES` directory are usually named according to the SPDX license identifier, they can presumably have other names if they contain `Valid-License-Identifier` or `SPDX-Exception-Identifier` tags.

> It seems to me any annotation scheme that wishes to be widely supported in `LICENSE` files really ought to be driven through the SPDX matching guidelines which various license detection tools implement to varying degrees.

That sounds like a good idea! I wasn't aware that the [SPDX matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines) go into such detail.

**Comment by kirelagin** [comment]
:(
