### ISSUE TITLE
Not detecting MIT License when using multiple rows of authors.

### ISSUE THREAD

**Issue by ptibom** [licensee/licensee#373]
### Describe the bug

Not detecting MIT License when using multiple rows of authors.

### Steps to reproduce the behavior

1. Use the following license https://choosealicense.com/licenses/mit/
2. Add multiple rows of authors such as:
> MIT License
>
> Copyright (c) 2019 Firstname Lastname, Firstname Lastname, Firstname Lastname,
> Firstname Lastname, Firstname Lastname, Firstname Lastname
>
> Permission is hereby granted, free of charge ...

You may see a live example here:
https://github.com/ptibom/Lidar-Simulator/blob/master/LICENSE

### Expected behavior

Should detect the MIT License. (Github should display the MIT License information)

**Comment by rgommers** [comment]
The same issue is true for the BSD 3-clause license. And probably other licenses too. Example from https://github.com/scipy/scipy/pull/10247:
``` 
Copyright (c) 2001, 2002 Enthought, Inc.
All rights reserved.

Copyright (c) 2003-2019 SciPy Developers.
```
fails, while
```
Copyright (c) 2001-2002 Enthought, Inc.  2003-2019, SciPy Developers.
```
works. We're lucky there's only 2 sets of copyrights holder so can work around the issue.

**Comment by mlinksva** [comment]
@rgommers  licensee can currently deal with multiple copyright lines, there just can't be anything in between them (like "All rights reserved" above). This ought work:

```
Copyright (c) 2001, 2002 Enthought, Inc.
Copyright (c) 2003-2019 SciPy Developers.
All rights reserved.
```

Here's the test:
https://github.com/licensee/licensee/blob/aa9bec625601c05db574b0c84af2bf716d97717e/spec/licensee/matchers/copyright_matcher_spec.rb#L32

and the relevant code:
https://github.com/licensee/licensee/blob/a94601cccb0f0756fe8fb59c9276e3c87bda8610/lib/licensee/matchers/copyright.rb#L10

(The pattern can repeat: `+`.)

To deal with wrapped copyright lines as reported by @ptibom some heuristic would have to be added to decide whether a line immediately following a copyright line looked like a wrap of the copyright line. I'm not sure that's common enough that it makes sense to try to handle given that it could cause problems eg where someone has deleted blank line that usually exists between copyright and license text.

**Comment by mlinksva** [comment]
One workaround for long copyright lines is to use `LICENSE.md` instead of `LICENSE` as the former will be rendered with long lines wrapped, avoiding one reason for manually wrapping.

**Comment by rgommers** [comment]
Thanks @mlinksva, that's very helpful.

**Comment by mlinksva** [comment]
I'm going to close this as I can't think of an easy to implement heuristic for detecting whether a list of copyright holders is multiline (and doesn't accidentally consume lines of license text, or ignore text that makes it a different license) and there are two workarounds -- multiple successive lines beginning with `Copyright`, or one long line in a `LICENSE.md` file.
