### ISSUE TITLE
Detection of identical license files not consistent

### ISSUE THREAD

**Issue by rgommers** [licensee/licensee#377]
### Describe the bug

The master repository at https://github.com/numpy/numpy says "View license", BSD-3 license is not recognized. My fork of that, https://github.com/rgommers/numpy, has identical `LICENSE.txt` and `LICENSES_bundled.txt` files in its master branch, and there the GitHub UI correctly says "BSD 3-Clause". I was testing on my fork how to finally get the right license reported in the GitHub UI (also had to split up the license info in two files (https://github.com/numpy/numpy/pull/13471) but that's another issue). The _only_ difference between my fork and its upstream is that upstream has a change in `setup.py` and `MANIFEST.in` for the license name.

### Steps to reproduce the behavior

1. Go to https://github.com/numpy/numpy and look at the license reported
2. Go to https://github.com/rgommers/numpy and look at the license reported

### Expected behavior

Behavior to be consistent between repos for identical license files.

**Comment by benbalter** [comment]
@rgommers Licensee detects both projects as BSD-3:

```
$ licensee detect --remote https://github.com/numpy/numpy
License:        BSD-3-Clause
Matched files:  LICENSE.txt
LICENSE.txt:
  Content hash:  d9f9648db9a253b749690f03af6bb7504e16dbcd
  Attribution:   Copyright (c) 2005-2019, NumPy Developers.
  Confidence:    98.71%
  Matcher:       Licensee::Matchers::Dice
  License:       BSD-3-Clause
  Closest non-matching licenses:
    BSD-3-Clause similarity:  98.71%
```

```
$ licensee detect --remote https://github.com/rgommers/numpy
License:        BSD-3-Clause
Matched files:  LICENSE.txt
LICENSE.txt:
  Content hash:  d9f9648db9a253b749690f03af6bb7504e16dbcd
  Attribution:   Copyright (c) 2005-2019, NumPy Developers.
  Confidence:    98.71%
  Matcher:       Licensee::Matchers::Dice
  License:       BSD-3-Clause
  Closest non-matching licenses:
    BSD-3-Clause similarity:  98.71%
```

Please see https://github.com/licensee/licensee/blob/master/docs/CONTRIBUTING.md#reporting-an-improperly-detected-license. If you are not able to reproduce the issue, I suspect it is a matter of the detected license being cached.

**Comment by rgommers** [comment]
Thank you for the quick reply @benbalter. 

> If you are not able to reproduce the issue, I suspect it is a matter of the detected license being cached.

Ah yes, looks like I should have opened a GitHub support request instead of this issue. Closing
