### ISSUE TITLE
BlueOak-1.0.0 license support

### ISSUE THREAD

**Issue by sskras** [licensee/licensee#379]
Correct me if I am wrong, but I think this project doesn't support **Blue Oak Model License** (BlueOak-1.0.0 for short).  I found about 90 repos using it ATM:

https://github.com/sskras/license-test/blob/7989cc7e99fa5696c186a514f03e52598331d1ad/repo-list-using-blueoak.md

It's looks like a permissive license [written by professional lawyers](https://blueoakcouncil.org/2019/03/06/model.html) to be simple and modern.  My questions:

1, can you add support for it, please?

2, how should I report it to Github so it can be added to the list? Currently it shows:

<kbd>
    <img src="https://user-images.githubusercontent.com/7887758/57591099-63883500-7538-11e9-925e-50e18c657bc4.png">
</kbd>

**Comment by benbalter** [comment]
Please see https://github.com/licensee/licensee/blob/master/docs/CONTRIBUTING.md#adding-a-license.
