### ISSUE TITLE
Unable to detect BSD 4-Cause license

### ISSUE THREAD

**Issue by alistair23** [licensee/licensee#386]
### Describe the bug

With the BSD 4-Clause license added to Choose a license https://github.com/github/choosealicense.com/pull/669 licensee is still unable to match the license.

### Steps to reproduce the behavior

1. Run ./script/cibuild using this PR https://github.com/github/choosealicense.com/pull/669

### Expected behavior

cibuild should identify the licenses as BSD 4-clause and the tests should pass.

### Additional context

The matching breaks as soon as there is a space in [fullname] or [project]. It looks like the BSD 3-Clause isn't so picky which I don't understand.  It looks like Licensee has to be updated first before the matcher will work here. They use the list of licenses from here though, so this seems like a chicken and egg problem.

**Comment by alistair23** [comment]
This still seems to be too strict as it doesn't match with BSD-4-Clause licenses

**Comment by mlinksva** [comment]
One of the examples you provide in https://github.com/github/choosealicense.com/pull/669, https://github.com/YosemiteLabs/yosemite-public-blockchain/blob/master/LICENSE comes very close (97.32%) despite being adulterated (eg "powered by")...

```
$ cat LICENSE | bundle exec bin/licensee diff --license=bsd-4-clause 
Comparing to BSD 4-Clause "Original" or "Old" License:
Input Length:      1615
License length:    1624
Similarity:      97.32%
diff --git a/LICENSE b/LICENSE
index eb217ee..a508a16 100644
--- a/LICENSE
+++ b/LICENSE
@@ -1,21 +1,21 @@
bsd 4-clause {+"original" or "old"+} license[-copyright (c) [year], [fullname] all rights reserved.-] redistribution and use in source and
binary forms, with or without modification, are permitted provided that the
following conditions are met: - redistributions of source code must retain the
above copyright notice, this list of conditions and the following disclaimer. -
redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution. - all advertising materials
mentioning features or use of this software must display the following
acknowledgement: [-this-]{+"powered by yosemite" or "this+} product includes software
developed by [-[project].-]{+yosemite x inc."+} - neither the name of [-the copyright holder-]{+yosemite x inc.+} nor the
names of its contributors may be used to endorse or promote products derived
from this software without specific prior written permission. this software is
provided by [-copyright holder-]{+yosemite x inc.+} "as is" and any express or implied warranties,
including, but not limited to, the implied warranties of merchantability and
fitness for a particular purpose are disclaimed. in no event shall [-copyright holder-]{+yosemite x+}
{+inc.+} be liable for any direct, indirect, incidental, special, exemplary, or
consequential damages (including, but not limited to, procurement of substitute
goods or services; loss of use, data, or profits; or business interruption)
however caused and on any theory of liability, whether in contract, strict
liability, or tort (including negligence or otherwise) arising in any way out of
the use of this software, even if advised of the possibility of such damage.
```

....and would if the extended title were accounted for (98.07%) in 

https://github.com/licensee/licensee/blob/aa9bec625601c05db574b0c84af2bf716d97717e/lib/licensee/license.rb#L95-L99

I think that can be generalized (match on spdx id or spdx title) so BSD-4-clause could match without being explicitly added to the alt title matching logic before the license is itself added. :smile:

I'll reopen this as a reminder to try that.

**Comment by alistair23** [comment]
Cool thanks! I also couldn't get https://github.com/alistair23/DashSight-Mezzanine-Card/blob/master/LICENSE to match which is a clean version of the BSD-4-Clause

**Comment by mlinksva** [comment]
Your repo does match in terms of "similarity" (99.24%) ... but the match is never tried because the difference in length is too great for bsd-4-clause to be a candidate. There might be something in #242 that I can pick to address that, but IIRC max_delta and similarity scoring are rather intertwined.

**Comment by alistair23** [comment]
Did you get a chance to look at something from https://github.com/licensee/licensee/pull/242?

**Comment by mlinksva** [comment]
@alistair23 yes in #391 which is pending review.

**Comment by alistair23** [comment]
Great! I'll keep an eye on that PR then.

**Comment by alistair23** [comment]
Ping. That PR must be close to being merged.
