### ISSUE TITLE
Minor license revisions in GPL 3.0 cause license misidentification

### ISSUE THREAD

**Issue by mbrukman** [licensee/licensee#387]
### Describe the bug

GPL 3.0 license changed slightly without updating the license version, as you can see in:

* [old] https://web.archive.org/web/20170914030415/http://www.gnu.org/licenses/gpl-3.0.txt
* [new] https://web.archive.org/web/20170930072152/http://www.gnu.org/licenses/gpl-3.0.txt

Licensee's GPL 3.0 file was updated accordingly in:

* https://github.com/licensee/licensee/pull/317/files#diff-cb5cb76367ec37937600f38e3193acb1

However, this means that previous versions of GPL 3.0 are no longer detected, forcing all projects to update to the new GPL 3.0 version to be detected correctly, or have their license displayed as "View license" which suggests they have a non-standard or proprietary license, when in fact, they are bona fide open-source projects.

### Steps to reproduce the behavior

As a result of the above change, projects such as [Mosh][mosh] which adopted the GPL 3.0 license with the [old] version above are not displaying "GPL 3.0" but "View license" instead (see screenshot below).

### Expected behavior

It would be preferable to detect all minor revisions of GPL 3.0 separately, not just the latest one, so that all projects don't have to keep updating their LICENSE file just to get their license identified correctly.

### Screenshots

E.g., [Mosh][mosh] displays the following:

![image](https://user-images.githubusercontent.com/4074659/60819973-83218f80-a16e-11e9-8a0b-6d19a4e84459.png)

> Thanks to @andersk for the research & references above in https://github.com/mobile-shell/mosh/pull/1050#issuecomment-508344199

[mosh]: https://github.com/mobile-shell/mosh

**Comment by mlinksva** [comment]
Licensee can deal with the slight change in the license text as it normalizes http[s] links. However that's not why mosh is seeing 'view license':

```
$ script/git-repo https://github.com/mobile-shell/mosh
License:        NOASSERTION
Matched files:  COPYING, COPYING.iOS, ocb-license.html
COPYING:
  Content hash:  b22f1b1f953a38a8a11686587b98831858d6468b
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-3.0
COPYING.iOS:
  Content hash:  31459ed641c78b0d5847362c6a17473f16a491e2
  License:       NOASSERTION
ocb-license.html:
  Content hash:  9bb197127289c6f1f5096454ea0b397e8978b751
  License:       NOASSERTION
```

It's the other two files, in the presence of which licensee can't make an overall conclusion.

This is expected behavior so closing. A workaround would be if mosh put the content of those other two files elsewhere (if that would work for it otherwise), perhaps a NOTICE file.

**Comment by mbrukman** [comment]
Thanks for the clarification, @mlinksva, and apologies for false alarm!
