### ISSUE TITLE
Detect licenses in /.github and /docs 

### ISSUE THREAD

**Issue by TheLocehiliosan** [licensee/licensee#398]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

In GitHub repositories, it is common practice to keep metadata about a project inside a `/.github` or `/docs` directory. The GitHub documentation itself refers to keeping readme, guidelines, conduct, and license data inside `/.github` or `/docs`. See [GitHub's About READMEs"](https://help.github.com/en/articles/about-readmes).

I contacted GitHub about this discrepancy, and it was suggested this would fit better as a feature of **licensee**. I think these locations make sense (in addition to a repository root) to store the license data.

I'm the author of software which manages dotfiles with Git. Many of my users want to include LICENSE information with their dotfiles, but not be forced to keep the LICENSE data at the root of their repository.

### Describe the solution you'd like

In addition to the root, inspect `/.github` and `/docs` for license data.

### Describe alternatives you've considered

...
### Additional context

...

**Comment by mlinksva** [comment]
This is not supported on purpose, see #250 and #335.
