### ISSUE TITLE
Add Licensee for LICENSE file

### ISSUE THREAD

**Issue by matzeeable** [licensee/licensee#403]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Some packages provide `LICENSE` or `LICENSE-MIT` files like this one: https://github.com/cowboy/javascript-sync-async-foreach

### Describe the solution you'd like

Perhaps it is possible to scan such files with https://licensee.github.io/licensee/ . It is a Ruby Gem so I do not know exactly how to implement.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by benbalter** [comment]
@matzeeable Can you elaborate on your request?

**Comment by matzeeable** [comment]
Sorry, I posted in the wrong forum. This thread should usually go to https://github.com/jslicense/licensee.js . Closed.
