### ISSUE TITLE
Short text about LGPL-3

### ISSUE THREAD

**Issue by AlexWayfer** [licensee/licensee#408]
### Describe the bug

Hello!

Can we detect LGPL-3 in a short text inside `README`? Or we should drop this short `License` section from `README`?

### Steps to reproduce the behavior

1. Clone https://github.com/r18n/r18n
2. Execute `licensee detect ./r18n-core/`
3. See `License: NOASSERTION` for `README.md`.

### Expected behavior

`LGPL-3.0`.

### Additional context

> R18n is licensed under the GNU Lesser General Public License version 3. See the LICENSE file or http://www.gnu.org/licenses/lgpl.html.

**Comment by mlinksva** [comment]
It looks like you dropped README#License, which is fair. You have license files in the subdirectory for each package maintained in the repo. Licensee doesn't look in subdirectories. If you want licensee to detect at the repo level, the easiest thing to do would be to add a license file at the top level.

Closing this as I don't have any good ideas for making the readme project file/reference matcher more robust, and I don't think it's a priority.

**Comment by AlexWayfer** [comment]
> It looks like you dropped README#License.

No, look at README inside `r18n-core`.

> Closing this as I don't have any good ideas for making the readme project file/reference matcher more robust, and I don't think it's a priority.

1. `licensee` has algorithm to detect licenses directly in `README`, not only as separated files, what you think is better.
2. This algorithm can be dropped **or**, I guess, improved. Like, `licensee` already detects `License` section in `README`. And probably it checks by full match of License text. Maybe we should also check the title of license in this section.
