### ISSUE TITLE
BSD-3 License is not detected for multiple copyright notes

### ISSUE THREAD

**Issue by ischoegl** [licensee/licensee#410]
### Describe the bug

Projects that draw from multiple sources are required to retain the original copyright notice (same for BSD-2, see [stackexchange question](https://opensource.stackexchange.com/questions/4531/can-i-combine-multiple-2-clause-bsd-license-files-into-one)).

If a second copyright is added, `licensee` no longer detects the license. 

### Steps to reproduce the behavior

In
```
BSD 3-Clause License

Copyright (c) 2010-2017, Foo Bar
All Rights Reserved

Copyright (c) 2018-2020, Jane Doe
All Rights Reserved

[BSD 3-Clause boilerplate]
```
the second copyright statement prevents detection.

### Expected behavior

License should be detected.

### Additional context

[SPDX](https://spdx.org/licenses/BSD-3-Clause.html) reference

**Comment by mlinksva** [comment]
This should be detected with current licensee:

```
BSD 3-Clause License

Copyright (c) 2010-2017, Foo Bar
Copyright (c) 2018-2020, Jane Doe
All Rights Reserved

[BSD 3-Clause boilerplate]
```

It's possible that it could look for other forms of repetition as well, as you point out.

**Comment by ischoegl** [comment]
in the case I came across, there is text that is not common to the Copyright notes (i.e. the ‘All Rights Reserved’ is not mandatory and can take other forms), see SPDX reference above.

**Comment by mlinksva** [comment]
I don't think we can handle some text other than all rights reserved that happens to follow a copyright line (the text could be significant) but repeated (c)\nARR as in the issue comment is simple enough to handle, and based purely on memory, strikes me as semi-common. Take a look at #412 as a potential fix.

**Comment by ischoegl** [comment]
I don't think that this is fixed, as [SPDX](https://spdx.org/licenses/BSD-3-Clause.html) lists those blocks as replaceable text. I.e. according to my reading, the entire block 'Copyright [...] Reserved' can be replaced - see *Replaceable Text* in [Matching Guidelines](https://spdx.org/license-list)
