### ISSUE TITLE
Detect REUSE license files

### ISSUE THREAD

**Issue by carmenbianca** [licensee/licensee#413]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

The [REUSE Specification](https://reuse.software/spec/) mandates that license files be put in `LICENSES/[spdx-identifier].[ext]`. These licenses are not detected by licensee.

### Describe the solution you'd like

licensee should detect the format `[spdx-identifier].[ext]` (or everything in the directory `LICENSES/`) as license files.

### Describe alternatives you've considered

N/A

### Additional context

licensee is used by ClearlyDefined, and ClearlyDefined currently fails to correctly identify REUSE-compliant packages. See https://github.com/fsfe/reuse-tool/issues/169

**Comment by mlinksva** [comment]
I'm not sure it would make sense for licensee to detect REUSE license files. They largely work on different scopes.

Licensee is mainly trying to (conservatively) detect the overall license for a project/repo, if there is one that can be identified.

REUSE is mainly about annotating the license of each individual file. The texts in LICENSES are merely supporting material for the individual file annotations and shouldn't be taken to indicate anything about the overall project license, even if there is only one file.

Am I missing something? If I am, what _exact_ behavior for licensee (or another tool operating at same scope) would you specify if it encounters REUSE license files in LICENSES?

**Comment by carmenbianca** [comment]
> REUSE is mainly about annotating the license of each individual file.

That's one big part of REUSE, yes. Certainly the most laborious part. But providing all used licenses is no less important.

Concretely, if you have a GPL-3.0-or-later project and copy+paste some Apache-2.0 code, this has the following consequences:

- Assuming you already provided the GPL-3.0 license text, you must now also provide the Apache-2.0 license text. Both of these texts go into `LICENSES/[spdx-identifier].[ext]`. `LICENSES/` should not contain any unused licenses.
- Effectively, your program is now licensed `GPL-3.0-or-later AND Apache-2.0`. Many projects do not do this and only list the main license or the "strongest" license as their outbound license. That is their discretion. Pinging @silverhook to make sure I didn't gaff here.

> what exact behavior for licensee (or another tool operating at same scope) would you specify if it encounters REUSE license files in LICENSES

As listed in the top post: All files in `LICENSES/[spdx-identifier].[ext]` are licenses under which some portion of the codebase is licensed. This effectively makes the outbound license `license1 AND license2 AND [...]`. Substitute [spdx-identifier] with a valid SPDX License Identifier and [ext] with some file extension, usually txt.
