### ISSUE TITLE
Detection when both LICENSE and COPYING file are present

### ISSUE THREAD

**Issue by filips123** [licensee/licensee#416]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Some GPL-licensed repositores are using both LICENSE and COPYING files. In that case, COPYING contains full license text (for example full GPLv3 text), while LICENSE contains short license headers, notices in case of using *or later* license, and licenses of dependencies.

### Describe the solution you'd like

* For example, [GIMP](https://github.com/GNOME/gimp) is licensed under GPLV3 or later and is using [COPYING](https://github.com/GNOME/gimp/blob/mainline/COPYING) file for standard license text, while [LICENSE](https://github.com/GNOME/gimp/blob/mainline/LICENSE) file contains short license notice as well as notice for the license of `libgimp` and other libraries. In this case, Licensee detects COPYING file as GPLv3 while LICENSE as NOASSERTION, so the whole project is detected as NOASSERTION.

  In this case, as LICENSE file doesn't have any particular format, it would probably be hard to detect it as GPLv3 or later, but it should still be able to detect repository as GPLv3 because of COPYING.

* Another example, [ZeroNet](https://github.com/HelloZeroNet/ZeroNet), is using GPLv3 and similar file structure. However, in this case, LICENSE file is using GNU's standard license header, so Licensee should detect it as GPLv3.

* In case if project is using a similar structure with standard header and GPLv3 *or later* license, this is often also specified in LICENSE file so it should be detected.

**Comment by mlinksva** [comment]
> In this case, as LICENSE file doesn't have any particular format, it would probably be hard to detect it as GPLv3 or later, but it should still be able to detect repository as GPLv3 because of COPYING.

This would be contrary to licensee's conservative project license identification. Only if every indicator it looks at detects the same license, it returns NOASSERTION: it errs on the side of false negative rather than false positive.

> In case if project is using a similar structure with standard header and GPLv3 _or later_ license, this is often also specified in LICENSE file so it should be detected.

In theory licensee could do this, consistent with its conservative project license identification. But it currently doesn't know anything about standard license headers. This would be a significant new feature.

**Comment by filips123** [comment]
It's probably still not fixed...
