### ISSUE TITLE
GPLv3 License not detected

### ISSUE THREAD

**Issue by theonlypwner** [licensee/licensee#417]
### Describe the bug

This [LICENSE.md](https://github.com/licensee/licensee/files/4362274/LICENSE.md.txt) (from [TheFox/GPLv3.md](https://github.com/TheFox/GPLv3.md/blob/c81a2afa53ca304c55724f3679ab4db746461cc2/gplv3.md)) is GPLv3, but licensee does not detect it, which makes GitHub show the license as "Other"

### Steps to reproduce the behavior

1. Create a GitHub repository.
2. Commit the attached `LICENSE.md` to the repo and push to GitHub.
3. Check license on GitHub.

### Expected behavior

I expect it to be shown as GPLv3.

#### Observed
![image](https://user-images.githubusercontent.com/802664/77216542-a3b52e00-6ae0-11ea-9109-e12eca50f544.png)

![image](https://user-images.githubusercontent.com/802664/77216547-ab74d280-6ae0-11ea-8b8e-e74c8aaba3c6.png)

#### Expected
![image](https://user-images.githubusercontent.com/802664/77216557-be87a280-6ae0-11ea-9a5d-4619ac998b06.png)

![image](https://user-images.githubusercontent.com/802664/77216559-c5161a00-6ae0-11ea-975a-d4883fb4b675.png)

**Comment by mlinksva** [comment]
You can fix this now by removing the trailing hashes on line 538 of your file.

#418 is an attempt at having licensee ignore these.

**Comment by theonlypwner** [comment]
I can confirm that the fix works, as GitHub recognizes the LICENSE.md as GPLv3 after removing trailing hashes on line 583.

I found the original source of the file at [TheFox/GPLv3.md](https://github.com/TheFox/GPLv3.md/blob/c81a2afa53ca304c55724f3679ab4db746461cc2/gplv3.md). I'm not sure why the contributors there added trailing hashes in TheFox/GPLv3.md@7eebed78c8451db19024966bcc7e320e0ac5775d.
