### ISSUE TITLE
Tag for third-party / linked components after main license

### ISSUE THREAD

**Issue by Nosferican** [licensee/licensee#424]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

There are many repositories on GitHub that fail to be detected by `licensee` / GitHub given the additional information about the license of third-party / linked components. For example, [JuliaLang/julia](https://github.com/JuliaLang/julia/blob/master/LICENSE.md) (MIT) or [ericphanson/UnbalancedOptimalTransport.jl](https://github.com/ericphanson/UnbalancedOptimalTransport.jl/blob/master/LICENSE) (MIT). Other repositories are a bit harder (e.g., [postgres/postgres](https://github.com/postgres/postgres)).

### Describe the solution you'd like

It would be great to have a public facing best practices in those scenarios to make the license machine detectable. For example, GitHub Choosealicense has material for choosing a license and how to put it in your repository but it does not cover cases such as third-party components, etc.

### Describe alternatives you've considered

Would be good to have a standard way of expressing that syntax such as `# Additional Components` or something or something like standardizing a header before the license with the `spdxID` or something.

### Additional context

Would love to hear what @mlinksva and @benbalter think it would be best practices for developers to adhere for "universal" machine-detectable.

**Comment by mlinksva** [comment]
@Nosferican a few partial solutions:

1. Move the additional license info to a `NOTICE` file. This won't interfere with license detection based on contents of a LICENSE or similar file (like licensee primarily does) but will get picked up by bill-of-materials type software, in part to account for one prominent license that requires preserving that file if it is present https://www.apache.org/licenses/LICENSE-2.0#redistribution
2. Specify the project license in a machine-readable file, usually a package manager file. Possibly this isn't done for Julia projects, at least I don't see a license field in https://julialang.github.io/Pkg.jl/v1/toml-files/index.html#Project.toml-1 (I'm unfamiliar with Julia though).
3. Like (2) but generic, and less common, specify the project license in a LICENSE.spdx file.

1 will (assuming the resulting LICENSE file is standard) allow licensee, including as enabled on github.com, to identify the project license. 2 and 3 will currently not generally allow licensee identify the project license where there is a non-identifiable LICENSE file (priority is to avoid false positives), but at least on the command line, licensee can tell you the license specified by the package or SPDX file (if it is a license licensee knows about, and a package manager or SPDX format it knows about).

That's a lot of caveats, but hopefully it helps. 😄 

p.s. There are (especially) venerable projects with complicated info for third party licenses in LICENSE or similar files eg https://github.com/mirror/xserver/blob/master/COPYING but https://github.com/postgres/postgres/blob/master/COPYRIGHT isn't much of an example of such though it does have a small amount of extra text and the PostgreSQL license has lots of fill-in fields making it hard for licensee to match at the level of confidence it requires to make an identificaiton.

**Comment by mlinksva** [comment]
Closing as I don't think there's anything here that could be implemented in licensee at this point. Feel free to continue discussion.
