### ISSUE TITLE
license detection fails at presence of a .pip-license-ignore file

### ISSUE THREAD

**Issue by joergbrech** [licensee/licensee#425]
### Describe the bug

Some [cookiecutter](https://github.com/cookiecutter/cookiecutter) templates add a file called `.pip-license-ignore` to the root of the repo. This file interferes with the license detection. This is the case for this [template](https://github.com/patdaburu/cookiecutter-click) for example.

### Steps to reproduce the behavior

1. Create a repo with a standard MIT license in `LICENSE` and a `.pip-license-ignore` file. Alternatively, create a repo with [this cookiecutter template](https://github.com/patdaburu/cookiecutter-click).
2. Run `script/git-repo [REPO-URL]`

   ```bash
   License:        NOASSERTION
   Matched files:  LICENSE, .pip-license-ignore
   LICENSE:
     Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
     Attribution:   Copyright YEAR NAME
     Confidence:    100.00%
     Matcher:       Licensee::Matchers::Exact
     License:       MIT
   .pip-license-ignore:
     Content hash:  4eb38d3abcbb0a4182eeae42d2a7dc8be303fae3
     License:       NOASSERTION
   ```

3. Rename `.pip-license-ignore` or delete it and run  `script/git-repo [REPO-URL]` again:

```bash
   License:        MIT
   Matched files:  LICENSE
   LICENSE:
     Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
     Attribution:   Copyright YEAR NAME
     Confidence:    100.00%
     Matcher:       Licensee::Matchers::Exact
     License:       MIT
   ```

**Comment by benbalter** [comment]
Perhaps we should ignore hidden files (files that start with `.`)?

**Comment by joergbrech** [comment]
That sounds reasonable to me!

**Comment by mlinksva** [comment]
In case anyone wishes to take this on as their first licensee PR, it should be easy to do in https://github.com/licensee/licensee/blob/master/lib/licensee/project_files/license_file.rb and adding a test in https://github.com/licensee/licensee/blob/master/spec/licensee/project_files/license_file_spec.rb
