### ISSUE TITLE
Reporting deliberatly `UNLICENSED` license selection

### ISSUE THREAD

**Issue by BigBlueHat** [licensee/licensee#429]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Licensee currently reports `NOASSERTION` for `package.json` files (at least) which use the `UNLICENSED` or `SEE LICENSE IN <filename>` patterns. This is typically used when there is deliberately no license being provided (vs. "no assertion" being made).

### Describe the solution you'd like

If `UNLICENSED` (and ideally `SEE LICENSE IN`) are detected in as the `license` value, those values should be reported by Licensee and _not_ the current `NOASSERTION`--which is technically incorrect.

### Describe alternatives you've considered

Leaving things as they are is probably the only other alternative available, and it sends the wrong message to the person running Licensee as jurisdictions differ on the implicit license given by making content publicly available without any license assertion--vs. explicitly saying that no license is provided (i.e. it's unlicensed) or that a less well known license is provided in a specific file.

### Additional context

Licensee is part of [repolinter](https://github.com/todogroup/repolinter/) and [licensed](https://github.com/github/licensed/) and many other tools for copyright/license code scanning (which is awesome! 😁). I'm currently putting tooling in place for enforcing open source usage policies at the company I work for and in my side-projects, and "accidentally" open sourcing something can be a real risk (especially at "scale"--i.e. lots of less informed developers).

This change would make it much more obvious (to the robots) that something should not be open sourced or (in the positive cases) that a deliberate action MUST be taken prior to its being open sourced.

`npm init` defaults to `ISC`, so accidentally tagged internal-only JS repos are no uncommon, but putting policy in place (backed by Licensee via repolinter) is currently hampered by this reporting bug.

I'm happy to send in a patch, but could use a pointer as to where best to put it. 😺 

Thanks for building this tool!
🎩

**Comment by mlinksva** [comment]
NOASSERTION is technically correct, see https://spdx.org/spdx-specification-21-web-version#h.2lwamvv

> jurisdictions differ on the implicit license given by making content publicly available without any license assertion

On the latter part, that's not what NOASSERTION means, on the first part, I've never heard of anyone relying on such differences.

> make it much more obvious (to the robots)

Whoever is programming the robots ought to take into account how other license tooling works!

This could probably be better documented. I'll look into doing that and leave this open in the meantime.

**Comment by BigBlueHat** [comment]
Well...sort of. 😃 I realize "UNLICENSED" is coming from NPM and not directly from SPDX. However, section 4.6 of the SPDX 2.1 spec includes the following:
>    * NOASSERTION, if:
>
> (i) the SPDX file creator has made no attempt to determine this field; or
>
> (ii) the SPDX file creator has intentionally provided no information (no meaning should be implied by doing so).

In the case(s) described here, that is decidedly _not_ the case. The "SPDX file creator" has explicitely stated a that the code is "UNLICENSED" (per the NPM community's practice...possibly others) or via the "SEE LICENSE IN <filename>" pattern.

Since the "SPDX file creator" has indeed declared a license, then the intent described in 4.6 should be met by displaying either "UNLICENSED" or "SEE LICENSE IN <filename>" (depending on which is provided):
> 4.6.2        Intent: Here, the intent is to provide the license information actually in the file, as compared to the Concluded License field.

Consequently, my expectation as an "SPDX file creator" is that I'd be shown the value of `license` even if it's not an SPDX compatible expression.

Right now, Licensee says there's NOASSERTION being made. The hope of this request is that it would instead tell me what assertion _is_ being made--even though it may not understand it.

Also, I'm more than happy to provide the code once we're 👍 that it should be added. 😃

**Comment by BigBlueHat** [comment]
It actually looks like the basic plumbing is there already:
https://github.com/licensee/licensee/blob/09d12227cee1b6c87b49b13f5c33a2eaf92d7280/lib/licensee/license.rb#L83

/me digs a bit more...

**Comment by mlinksva** [comment]
> Right now, Licensee says there's NOASSERTION being made.

No, Licensee is saying that it isn't making an assertion about what license it has detected.

**Comment by BigBlueHat** [comment]
But the SPDX file creator (i.e. me) is trying to make an assertion that a I'm explicitly *not* providing a license.

Is there another way to do that?

**Comment by mlinksva** [comment]
Are you actually creating an SPDX file? Usually the creator is a tool, analyzing license data provided by a project.

Anyway, not really. If your project has zero files that licensee thinks might contain license info, it will return `license: NONE`.

If you wish to promote the use of `UNLICENSED` or some other affirmative indicator of no license offered, I'd suggest getting it standardized by SPDX, then tools, perhaps including licensee, might take it up.

**Comment by BigBlueHat** [comment]
The use of `UNLICENSED` is already being promoted (for some years now) in the [NPM `package.json` documentation](https://docs.npmjs.com/files/package.json) (at least):
> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
>
> { "license": "UNLICENSED" }
>
> Consider also setting "private": true to prevent accidental publication.

Right now, running Licensee on a a `package.json` file using `"license": "UNLICENSED"` in this way gets this report:
```
License:        NOASSERTION
Matched files:  package.json
package.json:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::NpmBower
  License:     NOASSERTION
```

Which I'm asserting (heh) here is incorrect, and should indeed--as you just described--be returning `license: NONE` (or similar).

**Comment by mlinksva** [comment]
OK, that sounds fine for the NPM matcher. I think if you change

https://github.com/licensee/licensee/blob/0aa62b73272d3360fc5dec32cb0685f28836f109/lib/licensee/matchers/npm_bower.rb#L16

to something like

```ruby
if match && match[1]
 return 'no-license' if match[1] == 'UNLICENSED'
 match[1].downcase
end
```

Licensee will return NONE in the case you describe. Feel free to make a PR. Ideally add a test with it.
