### ISSUE TITLE
Dependency on coreutils not stated

### ISSUE THREAD

**Issue by lionellloh** [licensee/licensee#438]
### Describe the bug

The gen has a dependency on `coreutils` but the dependency is not mentioned anywhere. 

### Steps to reproduce the behavior

Assuming you have coreutils installed
```
brew uninstall coreutils
gem install licensee
```

### Expected behavior

I expected the installation to complete successfully. 

### Actual behavior
The installation fails without `coreutils`
```
current directory: /Users/lionellloh/.rvm/gems/ruby-2.4.0/gems/rugged-0.99.0/ext/rugged
make "DESTDIR=" install
make: /usr/local/opt/coreutils/bin/gmkdir: No such file or directory
make: *** [.sitearchdir.-.rugged.time] Error 1

make install failed, exit code 2
```

### Screenshots

![image](https://user-images.githubusercontent.com/29104062/84295003-9443ff00-ab7c-11ea-8be4-f30815d6f4a8.png)

### Additional context
I installed `coreutils` and subsequently, the installation of `licensee` worked.

### Suggestion: 
Include the fact that `coreutils` is required within the readme.

**Comment by lionellloh** [comment]
Apparently it is not mandatory to have `coreutils` installed so this issue's title is misguided. Could someone advice what the root cause is?

**Comment by david-a-wheeler** [comment]
I suspect that coreutils is only required if you are using MacOS and installed GNU make via brew.

MacOS is a Unix, but its BSD utilities are far less capable than the GNU versions. The "gmkdir" is probably a reference to the GNU version of mkdir. On a typical Linux system, the GNU utilities are already there.

**Comment by lionellloh** [comment]
I see, I think you are right. 

May I propose a fix that returns an informative print statement and suggest for the user to do a `brew install`?
