### ISSUE TITLE
Tri-license - MPL 1.1/GPL/LGPL - is not detected

### ISSUE THREAD

**Issue by eyalroz** [licensee/licensee#441]
### Describe the bug

The licensee gem - at least, as it is used by GitHub - fails to detect the Tri-license - MPL 1.1/GPL/LGPL.

### Steps to reproduce the behavior

1. Go to [The LICENSE file of the removedupes repository on GitHub](https://github.com/eyalroz/removedupes/blob/master/LICENSE)
2. Notice it's the  Tri-license - MPL 1.1/GPL/LGPL.
3. Now go to  [The removedupes repository main page](https://github.com/eyalroz/removedupes/)
4. Notice the license is not detected as anything specific.

### Expected behavior

I should see an indication that it's the tri-license.

### Screenshots

![Uploading Screenshot from 2020-06-27 01-03-21.png…]()

### Additional context

See [this thread](https://github.community/t/license-auto-identification-failing-for-tri-license-mpl-gpl-lgpl/119979) in the GitHub support forum.

**Comment by mlinksva** [comment]
Licensee the way it works currently never returns a positive license identification overall for a repo (which is the info GitHub is using) in the presence of multiple licenses. That ideally will be addressed eventually (emphasis on eventually), but I don't think the repo you provided could ever be detected, as the LICENSE file mentions some licenses, but barring AI, there's no way for a program to have confidence (licensee is conservative, would rather take false negatives than risk false positive) about making a positive identification that those licenses mentioned apply to the repository.

**Comment by eyalroz** [comment]
The question of what "confidence" means is a tricky one and I don't want to get into it. 

Regardless, in my example, I'm not using some custom wording. I copy-pasted a standard boilerplate text for the tri-license, and replaced my email address. Surely AI is not needed to identify that...

Also, while it's technically true that this file involves multiple licenses, the "tri-license" can be considered a sort-of-a license unto itself. You don't have to support a chimera license for every possible combination of licenses, but this one is prominent/famous enough - IMHO - to merit consideration as though it were a single license, until a generic solution is implemented sometime in the future.

With that said, I'd like to ask you consider reopening the bug report.
