### ISSUE TITLE
Please support GNU's FDL (Free Documentation License)

### ISSUE THREAD

**Issue by flatcap** [licensee/licensee#449]
I'd like **licensee** and hence **GitHub** to understand [GNU's Free Documentation License](https://www.gnu.org/licenses/fdl-1.3)

I've just created a repo (on GitHub) for some documentation and noticed that the FDL isn't recognised.
_licensee_ didn't recognise the license, either.

Checking the source, I see that you support several 'CC' licenses.
Please can you add support for FDL v1.3.

Thanks :heart:

**Comment by mlinksva** [comment]
Licensee vendors licenses from https://github.com/github/choosealicense.com/tree/gh-pages/_licenses

You can make a pull request there if you'd like to propose adding GFDL-1.3. For details see https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by StEvUgnIn** [comment]
If you need help, I'm here.

**Comment by yooksi** [comment]
Too bad FDL is not supported, GNU needs more love ❤️

**Comment by StEvUgnIn** [comment]
GNU has enough love

**Comment by StEvUgnIn** [comment]
@flatcap 
I can do this for you if it is too difficult for you

**Comment by flatcap** [comment]
In the beginning I just wanted GitHub to automatically recognise the FDL license.
It looked like a simple oversight.

But looking at the amount of work **I** needed to do, I realised that I don't care _that_ much.

@StEvUgnIn, if you have the time, patience and understanding to make this happen, **please** do.
I'd like to see FDL recognised and I can't be the only one.

Thanks

**Comment by StEvUgnIn** [comment]
The complexity is to add a license in three main versions and that share no similitude to most available licenses and suffers from being limited to document writing.

**Comment by StEvUgnIn** [comment]
I assert being non feasible to add the GFDL to choosealicense.com as every piece of documents require to be certified as GFDL. No LICENSE neither COPYING can be used to certifiy work. You may as well look for alternative licenses creative common, no-license, etc.
