### ISSUE TITLE
Does not detect "trimmed down" CC-BY-4.0

### ISSUE THREAD

**Issue by jeffmcaffer** [licensee/licensee#464]
### Describe the bug

The current baseline text for CC-BY-4.0 (https://github.com/licensee/licensee/blob/master/vendor/choosealicense.com/_licenses/cc-by-4.0.txt) includes all of the pre- and post-amble that discusses how to use the license etc. If a user trims off this extraneous content (basically lines 1-55 and 367-) then licensee only gives a 66% match and reports NOASSERTION (it also detected CC-BY-SA-4.0 with a 55% confidence).

### Steps to reproduce the behavior

1. Go to the license file in https://github.com/github/docs/pull/291
2. Run licensee on it
4. See that the result is NOASSERTION whereas the text in the file is the body of the CC-BY-4.0 license

### Expected behavior

Should report CC-BY-4.0 with 100% confidence

**Comment by jeffmcaffer** [comment]
Note this may also be an issue for the other CC licenses

**Comment by mlinksva** [comment]
It'd be easy enough to strip the optional text before comparing, as we already do for CC0-1.0, and for licenses with an "END OF TERMS AND CONDITIONS" marker.

However, some of the text at the end cut is not recognized to be optional by https://spdx.org/licenses/CC-BY-4.0.html -- possibly it should be, though I'd rather have it annotated by SPDX as such before accommodating (as [done for CC0-1.0](https://github.com/spdx/license-list-XML/search?type=issues&q=cc0+optional) IIRC).

**Comment by mlinksva** [comment]
https://github.com/spdx/license-list-XML/pull/1265 was merged today. When I get a bit of spare time (no promises; if anyone is eager to tackle this themselves, go for it; nokogiri's XML API looks reasonable) I plan to have licensee's content normalization leverage `<optional>` markup in SPDX XML and thus fix this issue, though I'll leave it closed as stale for now. 😄

**Comment by goneall** [comment]
Just FYI - there is a project to implement full SPDX license matching in Python - some of the approaches using Regex and normalizations may be a useful approach.

Here's a link to the project: https://github.com/m1kit/yalm-python
