### ISSUE TITLE
licensee identifies Solvitaire as "GPL-2.0" but GitHub does not show it as such

### ISSUE THREAD

**Issue by shlomif** [licensee/licensee#466]
### Describe the bug

licensee identifies [Solvitaire](https://github.com/thecharlieblake/Solvitaire) as "GPL-2.0" but GitHub does not show it as such. I tried both with and without `--no-remote`.:

```
[shlomif@telaviv1 ~]$ git clone https://github.com/thecharlieblake/Solvitaire
Cloning into 'Solvitaire'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 4827 (delta 50), reused 32 (delta 10), pack-reused 4720
Receiving objects: 100% (4827/4827), 7.80 MiB | 7.42 MiB/s, done.
Resolving deltas: 100% (2788/2788), done.
[shlomif@telaviv1 ~]$ cd Solvitaire
[shlomif@telaviv1 Solvitaire]$ licensee --version
zsh: command not found: licensee
[shlomif@telaviv1 Solvitaire]$ PATH=/home/shlomif/apps/prog/ruby-2.7.x/bin:"$PATH"
[shlomif@telaviv1 Solvitaire]$ licensee --version
License:  None
[shlomif@telaviv1 Solvitaire]$ licensee --no-remote
License:        GPL-2.0
Matched files:  LICENSE
LICENSE:
  Content hash:  3becd209e8ed8039656c1debe01dd17b9a79208f
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-2.0
[shlomif@telaviv1 Solvitaire]$ licensee
License:        GPL-2.0
Matched files:  LICENSE
LICENSE:
  Content hash:  3becd209e8ed8039656c1debe01dd17b9a79208f
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-2.0
[shlomif@telaviv1 Solvitaire]$ gem update licensee
Updating installed gems
Nothing to update
[shlomif@telaviv1 Solvitaire]$ 
```

On the other hand, https://github.com/thecharlieblake/Solvitaire shows "View license" and there is no license infobox in https://github.com/thecharlieblake/Solvitaire/blob/master/LICENSE .

How can it be fixed?

**Comment by benbalter** [comment]
Licensee is an open source project used by hosted services like GitHub which often  detect licenses using prior versions of Licensee and cache the result.

If you'd like to report that a license is improperly detected by a hosted service, please contact [GitHub support](https://github.com/contact) directly.

**Comment by shlomif** [comment]
> Licensee is an open source project used by hosted services like GitHub which often detect licenses using prior versions of Licensee and cache the result.
> 
> If you'd like to report that a license is improperly detected by a hosted service, please contact [GitHub support](https://github.com/contact) directly.

Thanks @benbalter ! I did that now.

**Comment by shlomif** [comment]
An update: the licence has been detected now: https://github.com/thecharlieblake/Solvitaire ; it is still not displayed in this search however: https://github.com/search?utf8=%E2%9C%93&q=solvitaire , but hopefully that too will be fixed in the not-too-far future. I also get a generic support auto-reply by E-mail from GitHub. Closing this issue for now.
