### ISSUE TITLE
Projects with modified Apache license are marked as Apache

### ISSUE THREAD

**Issue by tdunning** [licensee/licensee#474]
### Describe the bug

Projects that use a modified Apache license are being marked as Apache.

### Steps to reproduce the behavior

See https://github.com/PixarAnimationStudios/ruby-jss or https://github.com/PixarAnimationStudios/chook
Click on the license. It is a modified Apache license.

Note the license indicator on the project is listed as "Apache".
### Expected behavior

Any project that *modifies* clauses of the Apache license should be marked as non-standard. They may or may not be open source and the change may or may not matter. The fact is, however, nobody can trust an automated decision about that. Once you modify the license, you have to get your lawyer involved to understand the change.

**Comment by goneall** [comment]
Just a note - implementing the full license matching against the SPDX license templates would help resolve these types of issues.  Unfortunately, it is a rather complex algorithm.

A recent Community Bridge project implemented a Python algorithm which uses regular expressions: https://github.com/spdx/spdx-license-matcher

The Java code is a bit more (arguably too) complex: https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java

If anyone is interested in porting either of these to this project, I can provide help on the design/algorithm (although I'm not a Ruby programmer)

**Comment by mlinksva** [comment]
@goneall thanks for the pointers. I'd looked at the Java version long ago and it did look complex, I was not eager to translate. The Python implementation looks more straightforward, though at a glance it looks like it's using the license text (as opposed to template) -- how does it deal with optional text?

I've been wondering about what strikes me as a brute force regex approach -- turn each license's XML version into a regex, which incorporates all of the optional and alternative text in the XML version. I'm probably missing an obvious flaw in such an approach.

**Comment by tdunning** [comment]
The Apache license is a text document. As such, if you want to use it, you
need a textual LICENSE file.

IF you change that license by changing any clauses in any significant way,
then it isn't the Apache license any more. As such, simply downcasing and
collapsing spaces should be sufficient to find a match.

I don't know enough Ruby to suggest code, but I would be happy to build a
test case in, say, Java or Python if you would like to point me at a
thousand or so purported Apache projects. Or if you would prefer, I can
find them at random starting with all the Apache Software Foundation
projects and the known problematic Sony projects.

**Comment by goneall** [comment]
@mlinksva my bad - wrong repo.

The correct Python repo is https://github.com/spdx/spdx_python_licensematching

The license matching repo I pointed to earlier is used for a faster matching used in the online tools.

The approach used in the spdx_python_licensematching is very similar to the brute force method you are considering.

At first, I didn't think the regex approach would work, but after a few iterations, @anshuldutt21 got it to work reasonably well on a few test cases.

**Comment by tdunning** [comment]
So, @mlinksva and @goneall

How can I contribute here?

What is the next best step?

**Comment by benbalter** [comment]
> I've been wondering about what strikes me as a brute force regex approach -- turn each license's XML version into a regex, which incorporates all of the optional and alternative text in the XML version. I'm probably missing an obvious flaw in such an approach.

I had started down that path in https://github.com/licensee/licensee/pull/254, but was not and am not able to prioritize it.

**Comment by mlinksva** [comment]
Thanks for reporting this @tdunning . I've added the example you've provided to our test cases so that it doesn't recur as a false positive. We are heavily biased toward avoiding false positives over false negatives (most of the bug reports we receive are about the latter) and can always do more. The long term next step is probably to incorporate SPDX license matching rules and license templates into licensee -- those address the normalization and optional sections required to not go overboard on false negatives, including with Apache 2.0. The best place to contribute with Python and Java skills is probably in the SPDX project, which uses those languages, and helps the whole licensing community trend toward more standardization and best practices.

**Comment by goneall** [comment]
@tdunning The SPDX group definitely welcomes contributions.  The [Python libraries](https://github.com/spdx/tools-python) is an area in need of some work, although it is also suffering from low bandwidth from the maintainers of this library to review/accept PR's.

Another area that would be related to this issue is reviewing and adding test cases to the [spdx_python_licensematching](https://github.com/spdx/spdx_python_licensematching) library.  Once we have high confidence in this, perhaps we can find a Ruby developer interested in porting the code and leverage the existing work @benbalter has done.  I would also like to replace the Java implementation with the Python code in the [SPDX Online Tools](https://tools.spdx.org/app/).

**Comment by gstein** [comment]
I've got plenty of Python skills, along with interest to fix this for the Apache Software Foundation. @goneall : if I help to improve the spdx/tools-python code, will that flow through to **licensee** ? (given that licensee is ruby-based)

**Comment by mlinksva** [comment]
NB this issue will be closed soon with a fix and test for the license text reported here, though it may take some time for the fix to be deployed on GitHub (this repo isn't for GitHub support, only for licensee).

Python code would have to be ported, but it will be very useful to have an implementation to prove and translate, so I strongly encourage it.

**Comment by ShaneCurcuru** [comment]
Thanks all for the thoughtful discussion and fix. 

As a note for the future: the core issue from the ASF's point of view here: APACHE is the ASF's registered trademark for Apache software and other copyrighted materials provided by the ASF's many projects. Prominently displaying licensed under "Apache License 2.0" in the GitHub UI for projects that do not use the original, unmodified Apache 2.0 license is also damaging to the ASF's trademark.

Obviously work on license scanners relies on energy to improve them 8-) , but we definitely hope that decisions on when to display a canonical license note in the UI vs. **not** displaying the license note takes into account any trademarks that license authors may own  (i.e. if not assured it's the original license, default to not assuming it matches more often).

**Comment by tdunning** [comment]
On Tue, Jan 19, 2021 at 9:21 AM Shane Curcuru <notifications@github.com>
wrote:

> Thanks all for the thoughtful discussion and fix.
>
> As a note for the future: the core issue from the ASF's point of view
> here: APACHE is the ASF's registered trademark for Apache software and
> other copyrighted materials provided by the ASF's many projects.
> Prominently displaying licensed under "Apache License 2.0" in the GitHub UI
> for projects that do not use the original, unmodified Apache 2.0 license is
> also damaging to the ASF's trademark.
>

Yes. Clearly.


> Obviously work on license scanners relies on energy to improve them 8-) ,
> but we definitely hope that decisions on when to display a canonical
> license note in the UI vs. *not* displaying the license note takes into
> account any trademarks that license authors may own (i.e. if not assured
> it's the original license, default to not assuming it matches more often).
>
The biggest problems are of our own making, at their root. The two major
mechanisms are:

- the license has "assigned to Apache" in the middle of it. Lots of people
change this to "assigned to <mumble>". I know I did.
- the license on our web site has direction added to the end of it. Some
people remove this. Some don't. Some modify it

A secondary mechanism is that some people have the idea that putting a
header on a file is sufficient to license a file even when there is a
conflicting statement in a README.  See, for instance,
https://github.com/edoliberty/streaming-quantiles. There is no license file
and the README says no commercial use and the files say Apache. Which is it
really? What should github say? How should corporate entity X treat it?
(answers: don't know, not Apache, radioactive)

All of these factors make it hard to do a string match to get the answer.

But, yes, false negatives are better than false positives for displaying
the Apache license badge on github. And I think that all the players are
very much aware of that.

**Comment by pombredanne** [comment]
FYI, I filed a related issue in https://github.com/nexB/scancode-toolkit/issues/2410
and scancode-toolkit does already detect these ill-formed Apache licenses

**Comment by tdunning** [comment]
The one you found that mentioned orgpilation was the best one!
