### ISSUE TITLE
Error when specifying a bundler gem from a git repo

### ISSUE THREAD

**Issue by clinejj** [licensee/licensee#492]
### Describe the bug

I'm not totally sure if this is an issue with this library or should be filed at https://github.com/github/licensed due to how it uses this library, but when using a git repo for a bundler gem, licensee reports the following error:
```
Search root must be the project path directory or its ancestor
from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/dependency.rb:40:in `initialize'
        from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/sources/bundler.rb:17:in `initialize'
        from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/sources/bundler.rb:60:in `new'
        from /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/licensed-3.0.0/lib/licensed/sources/bundler.rb:60:in `block (2 levels) in enumerate_dependencies'
```
(this is used in conjunction with licensed)

My gemfile specifies:
```
gem 'active_admin_import', '>= 4.2.1.ruby3', git: 'https://github.com/Shelf-Life/active_admin_import'
```
At that line, it seems licensed is expecting a different folder than what the gem is installed to:
```
Search root must be the project path directory or its ancestor: /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/active_admin_import-4.2.1.ruby3 and /Users/john/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/active_admin_import-3997e99f222e
```
are defined for root and path at this line: https://github.com/licensee/licensee/blob/master/lib/licensee/projects/fs_project.rb#L23

### Steps to reproduce the behavior

1. Add the above gem to a gemfile for a Ruby project
2. Run `bundle install`
3. Run `gem install licensed`
4. Run `licensed cache`

### Expected behavior

`licensed` should run as expected with no errors.

**Comment by mlinksva** [comment]
It looks like it is an issue with licensed, please open an issue there. Thanks!
