### ISSUE TITLE
Support Asciidoc formatting of LICENSE files (LICENSE.adoc)

### ISSUE THREAD

**Issue by jjscheel** [licensee/licensee#496]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I would like GitHub to recognize LICENSE files in ASCIIDOC format (LICENSE.adoc).

### Describe the solution you'd like

While GitHub has extended their integrated files support to include ASCIIDOC much as they've done with MarkDown and others, this integration doesn't include support in the LICENSE detection.  This appears to be a limitation in the licensee gem.

### Describe alternatives you've considered

Use leave in plain text or migrate to MD.

### Additional context

This is a "suggestion" not a hard requirements.  I'm just wondering if you've considered this and have any plans to add this support in the next 3-6 months.  (I also suspect this is a slippery slope issue as the number of formats will only grow.)

I've checked the closed issues and don't see any discussion of this idea.

Sadly, I'm not a Ruby expert and thus proposing a patch would be a larger learning curve than time permits me at this point.

Thanks in advance for your patience with answering what can be viewed as a silly question.

**Comment by mlinksva** [comment]
I'd consider it ultra-low priority. Naive search https://github.com/search?q=filename%3ALICENSE.adoc https://github.com/search?q=filename%3ALICENSE.md shows .md is 10000 times more common than .adoc for LICENSE files. Licensee's markdown license support is already pretty fragile. If it'd be possible to add .adoc support without adding more fragility for plain and markdown, I wouldn't necessarily object, but again it's super low priority. Many things I'd implement before given time to do so.

**Comment by jjscheel** [comment]
Understand fully.  Appreciate the quick response and the insight, Mike.
