### ISSUE TITLE
Files including copyright in the name cause failure of detection

### ISSUE THREAD

**Issue by jolav** [licensee/licensee#497]
### Describe the bug

Files including copyright in the name cause failure of detection. I have tested copyright.txt and assetsCopyright.txt

#### repository detecting license
```sh
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/jolav/roguelike-online/license
  "license": {
    "key": "agpl-3.0",
    "name": "GNU Affero General Public License v3.0",
    "spdx_id": "AGPL-3.0",
    "url": "https://api.github.com/licenses/agpl-3.0",
    "node_id": "MDc6TGljZW5zZTE="
  }
```
You can check [github](https://github.com/jolav/roguelike-online) detecting license and showing it correctly.  
This worked after renamed copyright.txt to assets.txt. First i tried renaming copyright.txt to assetsCopyright.txt but didnt work

#### repository not detecting license
```sh
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/command-at-space/commandatspace.com/license
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  }
```
You can check [github](https://github.com/command-at-space/commandatspace.com) not detecting license ans only shows view license
Is not detecting license i think because of existence of copyright.txt

**Comment by mlinksva** [comment]
This is intended behavior. The presence of a copyright file introduces uncertainty about whether additional or contradictory terms apply, so licensee declines to positively identify a license.
