### ISSUE TITLE
Additional text after 100% match results in NOASSERTION

### ISSUE THREAD

**Issue by SamuraiAku** [licensee/licensee#498]
I have an MIT license file that returns a 100% match.  Then I want to add one line of text after the license saying something like 
`Please see THIRDPARTY.md for license information for other software used in this project`

That reduces the match to 86.92% and the license detected to NOASSERTION.

It looks like anything more than 3-4 random characters after the license text is enough to bring the match below 99% and get NOASSERTION.

Is there some sort of comment character I could add that would prevent licensee from processing that line and get me back up to 100%?

**Comment by mlinksva** [comment]
> Is there some sort of comment character I could add that would prevent licensee from processing that line and get me back up to 100%?

There is, but absolutely no promises it'll continue to work, e.g., if we eventually swapped the default matcher for one entirely driven by SPDX matching rules.

With that caveat, anything after a line consisting of `end of terms and conditions` is discarded.
