### ISSUE TITLE
MIT licenses without details filled in are recognised as valid MIT licenses

### ISSUE THREAD

**Issue by VehpuS** [licensee/licensee#500]
### Describe the bug

MIT licenses without details filled in are recognised as valid MIT licenses (at least in the Github UI).

### Steps to reproduce the behavior

1. Go to [a LICENSE file with unfilled author / year details](https://github.com/wix-incubator/sketch-symbol-legend/blob/bea4f949e6f7f154bf2b1713cd9be07ca8bab53e/LICENSE)
2. See that it is parsed as an MIT license.

### Expected behavior

Either don't accept this as an MIT license, or provide a warning / error that this license is not applicable without being properly filled in.

### Screenshots
![image](https://user-images.githubusercontent.com/3040818/129607639-ef16b46e-0963-4976-b8dc-f9df3521e39a.png)

**Comment by benbalter** [comment]
@VehpuS Are you referring to the copyright notice? While admittedly awkward in practice given the conditions of the MIT to include "the above copyright notice", I [do not believe the copyright notice is necessary to convey the license itself](https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/#do-you-even-need-a-copyright-notice), and thus the project is properly detected as MIT licensed.

**Comment by VehpuS** [comment]
First of all - I appreciate the link the blog :). If the MIT license is indeed applicable without specifying a copyright holder, then perhaps an error is too harsh. 

I would still argue that there is a difference between an MIT license lacking the clause altogether and a license with unfilled details, like the one I show in the bug. Perhaps not legally (though I'm not a lawyer and can't be certain of that) but definitely in the sense of a. Looking professional and b. Giving a user who want to include the work used complete confidence that the code can be legally used in derivative works.

While licensee is not a product like Black Duck, claiming to be a security / legal aid tool, I still think it is more valuable to provide a "positive" detection only when no issues exist. But that is definitely less clear cut if this in not a legal issue (one of the reasons for which I opened an issue as opposed to trying to fix it immediately 🙃).

**Comment by david-a-wheeler** [comment]
Caveat: I'm not a lawyer & I'm definitely not your lawyer :-).

However, I agree with @benbalter that I expect the lack of a formal copyright notice wouldn't change anything. Sure, it's not as nicely done as it could have been. However, if this ever went to court (unlikely), I think a judge or jury would have no trouble figuring out the intent.

When I use licensee (or any tool like it), my main worry is things that are much worse, like "no license at all". "Not as nicely done as it could be" is not ideal, but when you have thousands of reused components, this is almost certainly not your primarily legal concern :-).

**Comment by mlinksva** [comment]
Agree with @david-a-wheeler. It'd be interesting to output "Not as nicely done as it could be" hints, but that's currently beyond the scope of this project.
