### ISSUE TITLE
Error with licensee.gemspec using Windows

### ISSUE THREAD

**Issue by sehirsig** [licensee/licensee#507]
### Describe the bug
I followed [This](https://licensee.github.io/licensee/#installation) Tutorial.
While installing Licensee with "bundle install --path vendor/bundle" on Windows 10 I get this Bug. 
(I have Ruby30-x64 installed with the Windows RubyInstaller)

- PATH has no blank spaces! (That's not the problem)
```
C:\Users\<PATH>\Licensee\licensee-9.15.1>bundle install --path vendor/bundle
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag

[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `licensee.gemspec`: No such file or directory - git ls-files -z. Bundler cannot continue.

 #  from C:/Users/<PATH>/Licensee/licensee-9.15.1/licensee.gemspec:45
 #  -------------------------------------------
 #    ] & `git ls-files -z`.split("\0")
 >  end
 #  # frozen_string_literal: true
 #  -------------------------------------------
. Bundler cannot continue.

 #  from C:/Users/<PATH>/Licensee/licensee-9.15.1/Gemfile:5
 #  -------------------------------------------
 #
 >  gemspec
 #  # frozen_string_literal: true
 #  -------------------------------------------
```

### Steps to reproduce the behavior

1. Enter   "bundle install --path vendor/bundle" on a Windows 10 machine running Ruby from the Windows RubyInstaller
### Expected behavior

Bundler can`t find the Path

### Additional context

I **fixed** it by changing the something in the **gemfile**. 
Line 45 from 
-  ] & `git ls-files -z`.split("\0")
to 
-  ] & "git ls-files -z".split("\0")

After that change I had this output:
```
C:\<PATH>\Licensee\licensee-9.15.1>bundle install --path vendor/bundle
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
Fetching source index from https://rubygems.org/
```

**Comment by mlinksva** [comment]
If your fix doesn't break installation on Linux/MacOS, a PR would be very welcome.

**Comment by mlinksva** [comment]
Looking at this again 

> There was an error while loading `licensee.gemspec`: No such file or directory - git ls-files -z.

I suspect the problem is that `git` is not in your path.

The fix just causes the command not not execute, but does not fail because `split` is happy to operate on "git ls-files -z" as a string rather than the captured output of the command  \`git ls-files -z`.
