### ISSUE TITLE
SIL OFL v1.1 not being detected

### ISSUE THREAD

**Issue by ghost** [licensee/licensee#523]
### Description
I have got a project that uses the SIL OpenFont License v1.1, but it's detected as "Other".

### Steps to reproduce the behavior

1. Go to my project's GitHub page ~~here~~ (broken link, the project was deleted);
2. Open the `LICENSE` file;
3. See how it's copied from the [SIL OFL license's website](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web);
4. See also how it does not present the permissions, limitations and conditions of the license, as when it's detected.

### Expected behavior
I expected GitHub to detect that the license is indeed SIL OFL v1.1, as it did with other projects, such as [JetBrains Mono](https://github.com/JetBrains/JetBrainsMono).

**Comment by mlinksva** [comment]
Licensee currently doesn't know about reserved font names, and with one in the text it falls below its matching threshold.

I'd be open to a patch that accounts for reserved font names. It'd be kind of janky, but including in the copyright regex may be the right thing for now; in a way that'd reflect how reserved font names are part of the copyright text in https://github.com/spdx/license-list-XML/blob/23b581d6996c2db8b969d6c8529182ed1b27a628/src/OFL-1.1.xml#L14

**Comment by mlinksva** [comment]
Fixed by #546
