### ISSUE TITLE
README contains outdated bundler instructions

### ISSUE THREAD

**Issue by paulschreiber** [licensee/licensee#524]
### Describe the bug
README contains outdated bundler instructions. It states:

    bundle install --path vendor/bundle

However, running that command produces this warning:

    [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations,
    which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and
    stop using this flag

### Expected behavior

No warnings.

### Additional context
Ruby 2.7
bundler 2.1.4

**Comment by mlinksva** [comment]
Hmm, I've never used that flag, just working with the package installed in the source directory.

Feel free to submit a PR updating to current best practice.

I notice that the mention of Debian stretch is also two stable versions old.
