### ISSUE TITLE
How do i install?

### ISSUE THREAD

**Issue by slingring** [licensee/licensee#526]
wheres the .exe i need to check a license on a github, but dont know where to find the license, and the github website said to use this so.

**Comment by Tyler887** [comment]
In your Gemfile:
```ruby
gem 'licensee', git: 'https://github.com/licensee/licensee.git', branch: 'master'
```

**Comment by slingring** [comment]
> In your Gemfile:
> 
> ```ruby
> gem 'licensee', git: 'https://github.com/licensee/licensee.git', branch: 'master'
> ```

The link says “Page Invalid”
And the hell is a gem file? I don’t use linux?

**Comment by benbalter** [comment]
@slingring I've updated [the README](https://github.com/licensee/licensee#installation) with Ruby and Docker installation instructions. This project is not distributed as a compiled Windows binary, so you will need some familiarity with running either Ruby code or Docker containers within a windows environment. You could also consider using Codespaces if you do not want to set up the project locally.
