### ISSUE TITLE
Mulan Permissive Software License, Version 2 not being detected

### ISSUE THREAD

**Issue by hktkzyx** [licensee/licensee#529]
### Describe the bug

The GitHub project using Mulan PSL v2 license is detected as "Other".

### Steps to reproduce the behavior

1. Go to the GitHub page [here](https://github.com/opengauss-mirror/openGauss-server).
2. Open the `License` file.
3. See the license file is copied from the official [Mulan PSL v2 website](http://license.coscl.org.cn/MulanPSL2).

### Expected behavior

I expected GitHub to detect that the license is `MulanPSL-2.0`.

### Additional context

The Mulan PSL v2 license is approved by OSI and included in [chooselicense.com](https://choosealicense.com/licenses/mulanpsl-2.0/).

**Comment by benbalter** [comment]
As described in [the "Reporting an improperly detected license" section of the project's CONTRIBUTING file](https://github.com/licensee/licensee/blob/master/docs/CONTRIBUTING.md#reporting-an-improperly-detected-license), the project properly detects the license:

```
License:        NOASSERTION
Matched files:  License, COPYRIGHT
License:
  Content hash:  50fd2938f2078373c11d82241dc4502804deb3da
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MulanPSL-2.0
COPYRIGHT:
  Content hash:  0b2912641ae782c13d3a850a69f4a3be1e977c79
  License:       NOASSERTION
  Closest non-matching licenses:
    PostgreSQL similarity:  25.11%
    MS-RL similarity:       23.90%
    MS-PL similarity:       22.42%
```

Looking at [the release history](https://github.com/licensee/licensee/releases), MulanPSL detection support was added in https://github.com/licensee/licensee/pull/489, but has not yet been released in a stable version.

Once a new version of Licensee is released, the dependency would need to be updated within GitHub.com, and then the license should be detected as expected.

**Comment by hktkzyx** [comment]
Noted with thanks.
