### ISSUE TITLE
New `rubygems` release

### ISSUE THREAD

**Issue by timkrins** [licensee/licensee#604]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I'm attempting to bump some dependencies in our app, and see that the current `rubygems` `licensee` package is still fixed to `reverse_markdown ~> 1.0`

### Describe the solution you'd like

A new `rubygems` release.

### Describe alternatives you've considered

N/A

### Additional context

Dependabot created this PR which was merged, which does the relaxation of the dependency:
https://github.com/licensee/licensee/pull/587

**Comment by mlinksva** [comment]
It's definitely time for a new release. I'll try to get to it next week.

**Comment by mlinksva** [comment]
https://rubygems.org/gems/licensee/versions/9.15.3

**Comment by timkrins** [comment]
Thanks! Awesome
