### ISSUE TITLE
License "other" for https://github.com/apache/echarts

### ISSUE THREAD

**Issue by louim** [licensee/licensee#611]
### Describe the bug

Hello, I'm new to this project, but I think there is a detection problem for https://github.com/apache/echarts. I apologize in advance if this kind of problem has already been reported in the past. I'm using this gem in the context of the `licenced` gem.

### Steps to reproduce the behavior

1. run `bundle exec licensee detect https://github.com/apache/echarts
2. License is detected as "other"

### Expected behavior

License should be detected as "apache-2.0".
This is the output of the query
```
LICENSE:
  Content hash:  bec905d850e7f5dc2e2db78a950d4a9db560a0b8
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       Apache-2.0
README.md:
  Content hash:  bf69ea2264fad8dd2cb2cc551b715016de5cf5fc
  License:       NOASSERTION
  Closest non-matching licenses:
    WTFPL similarity:  5.50%
    0BSD similarity:   1.91%
    ISC similarity:    1.70%
package.json:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::NpmBower
  License:     Apache-2.0
```

My best guess is that because the readme contain this under **license**, it fails detection?:
> ECharts is available under the Apache License V2.

**Comment by mlinksva** [comment]
You guessed correctly. If it were `Apache License 2.0` or even `Apache License V2.0` it'd be detected. Seems reasonable to be tolerant of leaving the `.0` off if it is a dot zero license version.

The relevant code is 
https://github.com/licensee/licensee/blob/6da1b692ac9da8a4512223149f986059b14e4249/lib/licensee/license.rb#L144-L167

PR welcome (with a test probably in https://github.com/licensee/licensee/blob/6da1b692ac9da8a4512223149f986059b14e4249/spec/licensee/matchers/reference_matcher_spec.rb) or I'll get to it eventually.
