### ISSUE TITLE
Add support for license links

### ISSUE THREAD

**Issue by varunkumar** [licensee/licensee#619]
I have been using https://github.com/remy/mit-license for my repos. I have learnt recently that GitHub has a [license detection](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license) feature and provides information for well-known licenses. However, the license detection fails to read *.mit-licenses.org licenses.

Please add support for detection from license links. Does it make sense?

**Comment by varunkumar** [comment]
I can contribute the code if it conceptually makes sense.

**Comment by mlinksva** [comment]
I'm not enthusiastic about this. The links aren't even canonical (something like Creative Commons license URLs) and are subject to change.

**Comment by mlinksva** [comment]
In other words I don't want to encourage this practice. But if it were to become widespread would be happy to revisit supporting.

**Comment by Learningtosurvive** [comment]
I would really appriciate the help
