### ISSUE TITLE
License file `LICENSE.AGPLv3` not recognized

### ISSUE THREAD

**Issue by matheusmoreira** [licensee/licensee#638]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I often use the license's abbreviated name as an extension to the `LICENSE` file. This makes it clear at a glance what the license is and what the file itself will contain to anyone viewing the repository. For example:

  - `LICENCE.AGPLv3`
  - `LICENCE.MIT`

However, these file names do not match [Licensee's rules][rules].

### Describe the solution you'd like

I'd like Licensee's matchers to recognize my license files. It already matches a similar format `LICENSE-MIT` with a reasonably high score of `0.70`.

### Describe alternatives you've considered

I considered renaming my license files instead. It seems like a perfectly reasonable and useful convention though.

### Additional context

Are you open to a pull request that adds support for it?

[rules]: https://github.com/licensee/licensee/blob/main/lib/licensee/project_files/license_file.rb

**Comment by mlinksva** [comment]
Yes, feel free to open a pull request that adds support.

**Comment by matheusmoreira** [comment]
@mlinksva Just made PR #639. Any feedback is welcome.

During my testing, I realized that the reason my license file isn't being recognized is due to the contents of the file itself, not the extension. Licensee apparently requires the _full_ license text to be used. The short notice that the license itself instructed me to use is not recognized, not even with a lower confidencd level.

Should I open a separate issue for this?

**Comment by mlinksva** [comment]
Conceivably licensee could detect standard license headers (to extent available in SDPX XML versions, which licensee vendors, eg https://github.com/spdx/license-list-XML/blob/17632be2fcd4d4c2a9eda1202be2878baceb47b4/src/AGPL-3.0.xml#L14-L25) at lower confidence, though it's usually not the right thing to do -- eg Apache-2.0's standard header notice refers to "this file", which just doesn't make sense for licensing a project. Conceivably licensee could note that a header notice is in a ~LICENSE file and recommend replacing it with the full license text.

Feel free to open a new issue about this.

**Comment by matheusmoreira** [comment]
Thank you for your attention. After carefully re-reading the instructions in the license, I agree that the right thing to do is to include the full license in the text. As you said, it is the right thing to do.

It is true that licensee matches the license extensions so I will close this issue along with the pull request. Looks like I was a victim of the XY problem. Thanks again.
