### ISSUE TITLE
Exact PostgreSQL license text has < 70% match similarity

### ISSUE THREAD

**Issue by ankane** [licensee/licensee#640]
Hi, thanks for this project!

### Describe the bug

The exact PostgreSQL license text from the [PostgreSQL repo](https://github.com/postgres/postgres/blob/master/COPYRIGHT) and [license-list-XML repo](https://github.com/spdx/license-list-XML/blob/main/src/PostgreSQL.xml) has < 70% match similarity.

### Steps to reproduce the behavior

```sh
script/git-repo https://github.com/postgres/postgres.git
```

Output

```ruby
License:        NOASSERTION
Matched files:  COPYRIGHT
COPYRIGHT:
  Content hash:  ab358d1fbaeff7968689604ce5437da5f57b376e
  License:       NOASSERTION
  Closest non-matching licenses:
    PostgreSQL similarity:    69.35%
    BSD-2-Clause similarity:  48.65%
    MIT similarity:           44.64%
```

### Expected behavior

Very high similarity so the license is detected as `PostgreSQL` instead of `NOASSERTION`.

### Screenshots

n/a

### Additional context

n/a

**Comment by mlinksva** [comment]
This ought to match in a perfect world, but unsurprising it doesn't. Licensee currently doesn't know what to do with the parenthetical on line 2, doesn't recognize "portions of..." as copyright lines, and the non-generic [regents of the] university of california.

Eventually I'd like to have a matcher based on the license-list-XML templates that presumably could deal with all of the variation specified in those, but until then I could see adding support for "portions of" preceding a copyright statement, which would likely increase the % but not get over the current 98% threshold for positive identification.

**Comment by ankane** [comment]
Hey @mlinksva, thanks for the response. fwiw, I found this surprising as a user, but sounds like there may not be an easy fix.
