### ISSUE TITLE
license-path command return wrong path.

### ISSUE THREAD

**Issue by patlefort** [licensee/licensee#667]
### Describe the bug

The `license-path` command return the wrong path to the license.

### Steps to reproduce the behavior

1. For example, run `licensee license-path /path/to/my/repo`.
2. It will print the current working directory as in: `/current/working/directory/LICENSE`.

### Expected behavior

It should print `/path/to/my/repo/LICENSE` or just plain `LICENSE`.

**Comment by mlinksva** [comment]
Have never used this command myself until now, but can reproduce. Thanks for the report. A fix should also add a test to https://github.com/licensee/licensee/blob/11d9b83164ca68d4b75298970a0c1ab6780950c5/spec/licensee/commands/license_path_spec.rb which is obviously not testing this scenario.
