### ISSUE TITLE
add CeCiLL-B and CeCiLL-C License  

### ISSUE THREAD

**Issue by d0p1s4m4** [licensee/licensee#729]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

CeCiLL-B & CeCiLL-C licenses are missing.

### Describe the solution you'd like

I'd like support for `CECILL-B` and `CECILL-C`

### Additional context

CeCiLL-B official licence: 
 - https://cecill.info/licences/Licence_CeCILL-B_V1-fr.txt (fr)
 - https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt (en)

CeCiLL-C official licence:
 - https://cecill.info/licences/Licence_CeCILL-C_V1-fr.txt (fr)
 - https://cecill.info/licences/Licence_CeCILL-C_V1-en.txt (en)

**Comment by mlinksva** [comment]
Hi licenses used by licensee are sourced from https://github.com/github/choosealicense.com/ feel free to open an issue there, see https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license
