### ISSUE TITLE
Recognize LICENSE.<SPDX identifier> as a valid file for licenses

### ISSUE THREAD

**Issue by pandaninjas** [licensee/licensee#732]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

Licensee doesn't recognize filenames of the form `LICENSE.<SPDX identifier>`. For example it doesn't recognize `LICENSE.MPL-2.0` or `LICENSE.AGPL-3.0-only`, only recognizing `LICENSE.MPL` and `LICENSE.AGPL`
### Describe the solution you'd like
Licensee recognizes filenames of the form `LICENSE.<SPDX identifier>`

### Describe alternatives you've considered

Rename the files to similar extensions which licensee recognizes.

### Additional context

N/A

**Comment by mlinksva** [comment]
This is due to the `-` in the file extension. Licensee should certainly look at LICENSE files with a SPDX ID extension. Welcome a PR with tests, or I'll get to it eventually.

**Comment by oddstr13** [comment]
Having looked at the RegEx here, I think it is more likely due to be the presence of `.` in the version.
The matching pattern seems to generally be `\.[^./]+`, that is, one `.` followed by one or more characters not `.` or `/`

https://github.com/licensee/licensee/blob/8ade73de7759d82949f3493744846a04857ea02c/lib/licensee/project_files/license_file.rb#L8-L52

**Comment by pandaninjas** [comment]
> Having looked at the RegEx here, I think it is more likely due to be the presence of `.` in the version. The matching pattern seems to generally be `\.[^./]+`, that is, one `.` followed by one or more characters not `.` or `/`
> 
> https://github.com/licensee/licensee/blob/8ade73de7759d82949f3493744846a04857ea02c/lib/licensee/project_files/license_file.rb#L8-L52

Seems like `\.([^./]|.\d)+` can be used to match dots that form parts of version numbers

**Comment by mlinksva** [comment]
Thanks @pandaninjas and @oddstr13 !
