### ISSUE TITLE
Overconfidence

### ISSUE THREAD

**Issue by mat-k-witts** [licensee/licensee#747]
### Criteria for matching seems too low

I am using the [Living Licence 1.0.0](https://gitlab.com/living-code/living-license/-/blob/1fe5a9cd83d4d11c0f43e90fff11c4545665f187/living-license-1.0.0.md) for a project and the results I get from running this script are as follows:

1. 55.67% match with the Blue Oak Model 1.0.0 license with no modifications
2. 55.67% match with the Blue Oak Model 1.0.0 license when the markdown is not formatted as an active link
3. 57.97% match when the Blue Oak Model attribution text is removed entirely

These observations suggest to me that none of these results are sufficiently reliable matches to confidently assert the license as being the Blue Oak License 1.0.0 programmatically as is happening right now?

IT seems more sensible to use a more reliable criteria, perhaps a match of 95% or more perhaps?

### Steps to reproduce

1. Download the affected license <https://gitlab.com/living-code/living-license/-/raw/main/living-license-1.0.0.md?ref_type=heads&inline=false>
2. Run the `licensee detect` command
3. Remove the active link to the *Blue Oak* license
5. Repeat the `licensee detect` command
6. Remove the entire attribution line
7. Repeat the `licensee detect` command

### Expected resullts

I would not expect this package to assert an existing license when the match is only at a 50-60% confidence level. I would expect an 'unknown' or 'other' category when the confidence level is less than about 90-95% perhaps?

### Screenshots

![licensee-screenie](https://github.com/licensee/licensee/assets/83780461/21a42665-8c5d-49f0-a141-5488024d986b)
![screenie-2](https://github.com/licensee/licensee/assets/83780461/7384a9f0-688e-4f92-b106-fb76afb75d5b)

### Additional notes

The page <https://gitlab.com/living-code/living-source> INCORRECTLY shows this link:

This project is licensed under the Blue Oak Model License 1.0.0. [Learn more](https://blueoakcouncil.org/license/1.0.0)

The project is actually licensed under a derivative of that license NOT the Blue Oak License, which could have problematic legal effects for users of code licensed under this license.

**Comment by mlinksva** [comment]
You're seeing correct and expected behavior.  Note `License: NOASSERTION` and `Closest non-matching`. A 98% match is required for positive identification, which would look like `License: BlueOak-1.0.0`.

**Comment by mlinksva** [comment]
Added: I don't know what is causing GitLab to display a false positive license on your GitLab repo. If GitLab is using licensee, it should be a bug in GitLab. However, if this is not the case feel free to reopen with additional details.
