### ISSUE TITLE
ref tag not working on gem

### ISSUE THREAD

**Issue by yongyongsi** [licensee/licensee#763]
### Describe the bug

I am trying to execute a command in the format `licensee detect [path] --ref=v1.0.0`. However, the `--ref` tag behaves inconsistently depending on the environment.

**Working correctly:**

On Local PC (Docker): `docker run licensee detect [PATH] --ref=v1.0.0`

**Not working:**

In Dev Container (Ruby): `licensee detect [PATH] --ref=v1.0.0`
I suspect that when installing with gem install licensee, the --ref tag may not function properly. When executing the command, I receive the error:

`ERROR: "licensee detect" was called with arguments [[PATH], "--ref=v1.0.0"]`

### Additional context
I'm glad to see the feature you suggested has been implemented. It has made things much easier for me. Thank you for your effort!☺️

**Comment by mlinksva** [comment]
What is the output of `licensee version` in the not working case?

**Comment by yongyongsi** [comment]
9.16.0 version is 😂

**Comment by mlinksva** [comment]
That's the explanation. The feature was introduced in https://github.com/licensee/licensee/releases/tag/v9.17.0
